# Generated by Django 5.2.5 on 2025-08-29 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='packsize',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='packsize',
            name='packaging_type',
            field=models.CharField(choices=[('SINGLE', 'Single Pack'), ('BOX', 'Box/Carton')], default='SINGLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('GREEN', 'Green Tea'), ('BLACK', 'Black Tea')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='packsize',
            unique_together={('product', 'label', 'packaging_type')},
        ),
    ]
