# Generated by Django 5.2.5 on 2025-08-29 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_packsize_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='core.product'),
        ),
    ]
