# Generated by Django 5.2.5 on 2025-08-29 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_packsize_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='pack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='core.packsize'),
        ),
    ]
